"""
Camera calibration using ArUco marker.
Estimates intrinsic camera parameters based on marker detection.

Security: Input paths are validated. XML parsing includes error handling.
"""
import cv2
import numpy as np
import xml.etree.ElementTree as ET
import os

# Generated by GitHub Copilot
def load_scene_config(scene_path):
  """
  Load calibration parameters from XML scene file.
  
  Args:
    scene_path: Path to scene XML configuration file
    
  Returns:
    Dictionary with marker_size_mm and expected_distance_m
    
  Raises:
    FileNotFoundError: If scene file does not exist
    ET.ParseError: If XML is malformed
    ValueError: If required elements are missing
  """
  # Vérifie que le fichier XML existe avant de tenter l'ouverture
  if not os.path.exists(scene_path):
    raise FileNotFoundError(f"Scene file not found: {scene_path}")
  
  try:
    # Parse le fichier XML de configuration de la scène
    tree = ET.parse(scene_path)
    root = tree.getroot()

    # Cherche le bloc <calibration> qui contient les paramètres physiques du marqueur
    calib_elem = root.find('calibration')
    
    if calib_elem is None:
      raise ValueError("Missing 'calibration' element in XML")
    
    # Lit la taille physique du marqueur (en mm) et la distance attendue caméra-marqueur (en m)
    marker_size = calib_elem.find('marker_size_mm')
    distance = calib_elem.find('expected_distance_m')
    
    if marker_size is None or distance is None:
      raise ValueError("Missing required calibration parameters in XML")
    
    return {
      'marker_size_mm': float(marker_size.text),
      'expected_distance_m': float(distance.text)
    }
  except ET.ParseError as e:
    raise ET.ParseError(f"Invalid XML in {scene_path}: {e}")

# Generated by GitHub Copilot
def calibrate_camera(image_path, scene_path):
  """
  Estimate camera intrinsic parameters using ArUco marker.
  
  Args:
    image_path: Path to captured marker image
    scene_path: Path to scene XML configuration
  
  Returns:
    Tuple of (camera_matrix, distortion_coefficients) or (None, None) if no marker detected
    
  Raises:
    ValueError: If image cannot be loaded
    FileNotFoundError: If scene file not found
  """
  # Valide que l'image existe avant de tenter la lecture
  if not os.path.exists(image_path):
    raise ValueError(f"Image file not found: {image_path}")
  
  # Charge l'image en mémoire (format BGR par défaut avec OpenCV)
  image = cv2.imread(image_path)
  if image is None:
    raise ValueError(f"Cannot load image: {image_path}")
  
  try:
    # Charge la taille physique du marqueur et la distance caméra-marqueur depuis le XML
    config = load_scene_config(scene_path)

    # Convertit en niveaux de gris — la détection ArUco fonctionne sur image mono-canal
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    
    # Initialise le dictionnaire ArUco (6x6 bits, 250 marqueurs disponibles)
    aruco_dict = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_6X6_250)
    parameters = cv2.aruco.DetectorParameters()
    detector = cv2.aruco.ArucoDetector(aruco_dict, parameters)
    
    # Détecte les marqueurs dans l'image: corners = coins des marqueurs, ids = identifiants
    corners, ids, _ = detector.detectMarkers(gray)
    
    if ids is None or len(ids) == 0:
      print("No markers detected for calibration")
      return None, None
    
    # Convertit la taille du marqueur de mm en mètres pour le calcul de la focale
    marker_size = config['marker_size_mm'] / 1000.0

    # Prend les coins du premier marqueur détecté (en pixels)
    marker_corners = corners[0][0]

    # Calcule la largeur du marqueur en pixels (distance euclidienne entre coin 0 et coin 1)
    marker_width_px = np.linalg.norm(marker_corners[1] - marker_corners[0])
    
    # Récupère la distance attendue caméra-marqueur depuis la config
    distance = config['expected_distance_m']

    # Estime la longueur focale f par la relation sténopé:
    # f = (taille_en_pixels × distance_réelle) / taille_physique_en_mètres
    focal_length = (marker_width_px * distance) / marker_size
    
    # Construit la matrice intrinsèque caméra K:
    # K = [[f, 0, cx],
    #      [0, f, cy],
    #      [0, 0,  1]]
    # où cx, cy est le point principal (centre de l'image)
    h, w = gray.shape
    camera_matrix = np.array([
      [focal_length, 0, w/2],
      [0, focal_length, h/2],
      [0, 0, 1]
    ], dtype=np.float32)
    
    # Coefficients de distorsion mis à zéro (pas de correction radiale appliquée ici)
    distortion_coeff = np.zeros((4, 1), dtype=np.float32)
    
    print(f"Estimated focal length: {focal_length:.2f}px")
    print(f"Camera matrix:\n{camera_matrix}")
    
    return camera_matrix, distortion_coeff
    
  finally:
    # Libère explicitement la mémoire occupée par l'image (bonne pratique green software)
    del image

if __name__ == "__main__":
  # Generated by GitHub Copilot
  ARUCO_DIR = os.path.dirname(os.path.abspath(__file__))
  ROBOT_DIR = os.path.dirname(ARUCO_DIR)
  image_path = os.path.join(ROBOT_DIR, 'marker_42.png')
  scene_path = os.path.join(ARUCO_DIR, 'aruco_scene.xml')
  
  try:
    camera_matrix, dist_coeff = calibrate_camera(image_path, scene_path)
    if camera_matrix is not None:
      print("Calibration successful!")
  except (FileNotFoundError, ValueError, ET.ParseError) as e:
    print(f"Error: {e}")