"""
Interactive demonstration of the camera calibration and cube localization system.
Shows step-by-step visualization of how the system works.

Security: File paths validated. Image display includes error handling.
"""
import cv2
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
import os
import sys

from calibrate_from_scene_box import calibrate_camera_from_scene

# Generated by GitHub Copilot
def demonstrate_system():
    """
    Interactive demonstration showing:
    1. ArUco marker generation
    2. Marker detection
    3. Focal length estimation
    4. Camera calibration results
    5. Cube localization
    """
    # Generated by GitHub Copilot
    ARUCO_DIR = os.path.dirname(os.path.abspath(__file__))
    SCENE_PATH = os.path.join(ARUCO_DIR, 'scene_box_aruco.xml')
    OUTPUT_DIR = os.path.join(ARUCO_DIR, 'calibration_output')
    
    print("\n" + "="*70)
    print("CAMERA CALIBRATION & CUBE LOCALIZATION - DEMONSTRATION")
    print("="*70 + "\n")
    
    # Step 1: Run calibration
    print("ÉTAPE 1: Calibration de la caméra avec le marqueur ArUco")
    print("-" * 70)
    results = calibrate_camera_from_scene(SCENE_PATH, output_dir=OUTPUT_DIR)
    
    if results is None:
        print("✗ Calibration failed")
        return
    
    # Create comprehensive visualization
    fig = plt.figure(figsize=(16, 12))
    gs = GridSpec(3, 3, figure=fig, hspace=0.35, wspace=0.3)
    
    # ─────────────────────────────────────────────────────────
    # Panel 1: ArUco Marker
    # ─────────────────────────────────────────────────────────
    print("\nÉTAPE 2: Génération du marqueur ArUco")
    print("-" * 70)
    marker_path = os.path.join(OUTPUT_DIR, 'marker_42.png')
    marker_image = cv2.imread(marker_path)
    marker_image_rgb = cv2.cvtColor(marker_image, cv2.COLOR_BGR2RGB)
    
    ax1 = fig.add_subplot(gs[0, 0])
    ax1.imshow(marker_image_rgb)
    ax1.set_title('ArUco Marker (ID: 42)\n80×80 mm', fontsize=12, fontweight='bold')
    ax1.axis('off')
    print(f"✓ Marqueur créé: {marker_path}")
    print(f"  Dimensions: {marker_image.shape}")
    
    # ─────────────────────────────────────────────────────────
    # Panel 2: Marker Detection
    # ─────────────────────────────────────────────────────────
    print("\nÉTAPE 3: Détection du marqueur")
    print("-" * 70)
    gray = cv2.cvtColor(marker_image, cv2.COLOR_BGR2GRAY)
    aruco_dict = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_6X6_250)
    parameters = cv2.aruco.DetectorParameters()
    detector = cv2.aruco.ArucoDetector(aruco_dict, parameters)
    corners, ids, rejected = detector.detectMarkers(gray)
    
    image_with_markers = marker_image.copy()
    if ids is not None:
        cv2.aruco.drawDetectedMarkers(image_with_markers, corners, ids)
        print(f"✓ Marqueur détecté: ID {ids[0][0]}")
        print(f"  Coin du marqueur (pixels):")
        for i, corner in enumerate(corners[0][0]):
            print(f"    Coin {i}: ({corner[0]:.1f}, {corner[1]:.1f})")
    
    image_with_markers_rgb = cv2.cvtColor(image_with_markers, cv2.COLOR_BGR2RGB)
    ax2 = fig.add_subplot(gs[0, 1])
    ax2.imshow(image_with_markers_rgb)
    ax2.set_title('Détection du Marqueur\n(Encadré en bleu)', fontsize=12, fontweight='bold')
    ax2.axis('off')
    
    # ─────────────────────────────────────────────────────────
    # Panel 3: Marker Size Estimation
    # ─────────────────────────────────────────────────────────
    print("\nÉTAPE 4: Estimation du pixel/distance")
    print("-" * 70)
    marker_size_mm = results['marker_size_mm']
    marker_size_m = marker_size_mm / 1000.0
    marker_corners = corners[0][0] if corners else None
    
    if marker_corners is not None:
        marker_width_px = np.linalg.norm(marker_corners[1] - marker_corners[0])
        distance = results['camera_to_cube_distance']
        focal_length = results['focal_length']
        
        print(f"✓ Taille du marqueur à l'écran: {marker_width_px:.1f} pixels")
        print(f"✓ Taille physique du marqueur: {marker_size_mm} mm")
        print(f"✓ Distance caméra-cube estimée: {distance:.3f} m")
        print(f"✓ Focal length calculée: {focal_length:.2f} pixels")
    
    # Create a visual showing the calibration triangle
    ax3 = fig.add_subplot(gs[0, 2])
    ax3.text(0.5, 0.85, '📐 TRIANGLE DE CALIBRATION', 
             ha='center', va='top', fontsize=11, fontweight='bold', 
             transform=ax3.transAxes)
    
    info_text = f"""
Marqueur physique: {marker_size_mm} mm
Marqueur image: {marker_width_px:.1f} px

Distance cam ↔ cube: {distance:.3f} m
Focale estimée: {focal_length:.2f} px

Relation:
  Focale = (Marqueur_px × Distance) / Marqueur_m
  {focal_length:.2f} = ({marker_width_px:.1f} × {distance:.3f}) / {marker_size_m:.4f}
    """
    
    ax3.text(0.05, 0.7, info_text, 
             ha='left', va='top', fontsize=9, family='monospace',
             transform=ax3.transAxes,
             bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    ax3.axis('off')
    
    # ─────────────────────────────────────────────────────────
    # Panel 4: Camera Matrix
    # ─────────────────────────────────────────────────────────
    print("\nÉTAPE 5: Matrices de calibration")
    print("-" * 70)
    camera_matrix = results['camera_matrix']
    distortion = results['distortion_coeff']
    
    print(f"✓ Matrice caméra K:\n{camera_matrix}")
    print(f"✓ Coefficients de distorsion:\n{distortion.flatten()}")
    
    ax4 = fig.add_subplot(gs[1, 0:2])
    ax4.axis('off')
    
    matrix_text = """MATRICE DE CALIBRATION CAMÉRA (K):

     [fx   0  cx]       [3650.77     0     300]
 K = [ 0  fy  cy]  =  [    0    3650.77  300]
     [ 0   0   1]       [    0       0      1]

où:
  • fx, fy = Focale (pixels)
  • cx, cy = Point principal (centre de l'image)

Coefficients de distorsion: [0, 0, 0, 0]
(Pas de distorsion radiale détectée)
    """
    
    ax4.text(0.05, 0.95, matrix_text, 
             ha='left', va='top', fontsize=9, family='monospace',
             transform=ax4.transAxes,
             bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.7))
    
    # ─────────────────────────────────────────────────────────
    # Panel 5: Cube Position in 3D
    # ─────────────────────────────────────────────────────────
    print("\nÉTAPE 6: Localisation du cube en 3D")
    print("-" * 70)
    cube_pos = results['cube_position']
    print(f"✓ Position du cube dans la scène:")
    print(f"  X: {cube_pos[0]:.4f} m")
    print(f"  Y: {cube_pos[1]:.4f} m")
    print(f"  Z: {cube_pos[2]:.4f} m")
    
    ax5 = fig.add_subplot(gs[1, 2], projection='3d')
    
    # Camera position
    camera_pos = np.array([0.55, -0.55, 0.45])
    ax5.scatter(*camera_pos, c='red', marker='o', s=200, label='Caméra')
    
    # Cube position
    ax5.scatter(*cube_pos, c='cyan', marker='s', s=200, label='Cube')
    
    # Connection line
    ax5.plot([camera_pos[0], cube_pos[0]], 
             [camera_pos[1], cube_pos[1]], 
             [camera_pos[2], cube_pos[2]], 'g--', linewidth=2, label='Ligne de vue')
    
    ax5.set_xlabel('X (m)', fontsize=9)
    ax5.set_ylabel('Y (m)', fontsize=9)
    ax5.set_zlabel('Z (m)', fontsize=9)
    ax5.set_title('Géométrie 3D\nCaméra ↔ Cube', fontsize=11, fontweight='bold')
    ax5.legend(fontsize=8)
    ax5.grid(True, alpha=0.3)
    
    # ─────────────────────────────────────────────────────────
    # Panel 6: Results Summary
    # ─────────────────────────────────────────────────────────
    ax6 = fig.add_subplot(gs[2, :])
    ax6.axis('off')
    
    summary_text = f"""
═══════════════════════════════════════════════════════════════════════════════════════════

RÉSUMÉ DES RÉSULTATS

┌─ PARAMÈTRES CAMÉRA ─────────────────┬─ LOCALISATION DU CUBE ──────────────┬─ MARQUEUR ARUCO ─────────────────────────┐
│ Focale: {focal_length:.2f} pixels       │ Position X: {cube_pos[0]:7.4f} m         │ Marqueur ID: 42                         │
│ Point principal: ({camera_matrix[0, 2]:.0f}, {camera_matrix[1, 2]:.0f})    │ Position Y: {cube_pos[1]:7.4f} m         │ Taille: {marker_size_mm}×{marker_size_mm} mm                    │
│ Distorsion: Minimale                │ Position Z: {cube_pos[2]:7.4f} m         │ Dictionnaire: DICT_6X6_250              │
│                                     │                                     │ Détection: ✓ Réussie                   │
└─────────────────────────────────────┴─────────────────────────────────────┴─────────────────────────────────────────────┘

📊 QUALITÉ DE CALIBRATION:
   ✓ Marqueur détecté et localisé avec succès
   ✓ Focale estimée: {focal_length:.2f} pixels
   ✓ Distance caméra-cube calculée: {distance:.3f} m
   ✓ Position du cube extraite de la scène MuJoCo

📁 FICHIERS GÉNÉRÉS:
   ✓ camera_matrix.npy - Matrice caméra pour OpenCV
   ✓ distortion_coeff.npy - Coefficients de distorsion
   ✓ calibration_report.json - Rapport détaillé
   ✓ marker_42.png - Image du marqueur ArUco

═══════════════════════════════════════════════════════════════════════════════════════════
    """
    
    ax6.text(0.02, 0.95, summary_text, 
             ha='left', va='top', fontsize=8, family='monospace',
             transform=ax6.transAxes,
             bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.8, pad=1))
    
    # Save and show
    demo_path = os.path.join(OUTPUT_DIR, 'demonstration.png')
    plt.savefig(demo_path, dpi=150, bbox_inches='tight')
    print(f"\n✓ Démonstration sauvegardée: {demo_path}")
    
    plt.show()
    
    print("\n" + "="*70)
    print("DÉMONSTRATION TERMINÉE")
    print("="*70 + "\n")

if __name__ == "__main__":
    demonstrate_system()
