"""
Cube position estimation from a moving camera using ArUco marker.
Uses the calibrated camera matrix K to solve the PnP problem and recover
the 3D pose (rotation + translation) of the marker in the camera frame.

Security: File paths validated. Numeric inputs sanitized.
"""
import cv2
import numpy as np
import os
import sys

# Generated by GitHub Copilot
def load_calibration(calibration_dir):
    """
    Load camera matrix and distortion coefficients saved by the calibration script.

    Args:
        calibration_dir: Path to the folder containing camera_matrix.npy and distortion_coeff.npy

    Returns:
        Tuple of (camera_matrix, distortion_coeff)
    """
    camera_matrix = np.load(os.path.join(calibration_dir, 'camera_matrix.npy'))
    distortion_coeff = np.load(os.path.join(calibration_dir, 'distortion_coeff.npy'))
    print("✓ Calibration chargée")
    print(f"  Focale fx={camera_matrix[0,0]:.2f} px, fy={camera_matrix[1,1]:.2f} px")
    print(f"  Point principal: ({camera_matrix[0,2]:.1f}, {camera_matrix[1,2]:.1f})")
    return camera_matrix, distortion_coeff


# Generated by GitHub Copilot
def estimate_cube_pose(image, camera_matrix, distortion_coeff, marker_size_m=0.08):
    """
    Estimate the 3D position and orientation of the cube in the camera frame.

    The marker is physically attached to the cube face, so the marker pose = cube pose.

    The PnP (Perspective-n-Point) problem is solved using the 4 corners of the
    detected marker:
      - The 3D corners are known in the marker's local frame (object points).
      - The 2D corners come from the image (image points).
      - solvePnP finds the rotation R and translation t such that:
            x_image = K * [R | t] * X_world

    Args:
        image: BGR image (numpy array) captured by the camera
        camera_matrix: 3×3 intrinsic matrix K from calibration
        distortion_coeff: Distortion coefficients from calibration
        marker_size_m: Physical side length of the ArUco marker in metres

    Returns:
        Dictionary with:
          - position_camera_frame: [x, y, z] position of the cube in camera frame (metres)
          - rvec: Rotation vector (Rodrigues)
          - tvec: Translation vector = position in camera frame
          - corners: Detected marker corners in the image (pixels)
        or None if no marker is detected.
    """
    # Convertit en niveaux de gris pour la détection
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Initialise le détecteur avec le même dictionnaire que lors de la calibration
    aruco_dict = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_6X6_250)
    parameters = cv2.aruco.DetectorParameters()
    detector = cv2.aruco.ArucoDetector(aruco_dict, parameters)

    corners, ids, _ = detector.detectMarkers(gray)

    if ids is None or len(ids) == 0:
        print("✗ Aucun marqueur détecté dans l'image")
        return None

    print(f"✓ Marqueur détecté: ID {ids[0][0]}")

    # Définit les 4 coins du marqueur dans son repère local (centre = origine)
    # Les coins sont dans l'ordre: haut-gauche, haut-droit, bas-droit, bas-gauche
    half = marker_size_m / 2.0
    object_points = np.array([
        [-half,  half, 0],   # Coin 0: haut-gauche
        [ half,  half, 0],   # Coin 1: haut-droit
        [ half, -half, 0],   # Coin 2: bas-droit
        [-half, -half, 0],   # Coin 3: bas-gauche
    ], dtype=np.float32)

    # Récupère les coins 2D détectés dans l'image (en pixels)
    image_points = corners[0][0].astype(np.float32)

    # Résout le problème PnP: trouve rvec (rotation) et tvec (translation)
    # tvec est le vecteur du centre de la caméra vers le marqueur, exprimé dans le repère caméra
    success, rvec, tvec = cv2.solvePnP(
        object_points,
        image_points,
        camera_matrix,
        distortion_coeff,
        flags=cv2.SOLVEPNP_ITERATIVE  # Méthode itérative — la plus fiable pour 4 points
    )

    if not success:
        print("✗ solvePnP a échoué")
        return None

    # tvec = [x, y, z] position du cube dans le repère caméra (en mètres)
    position = tvec.flatten()

    print(f"\n--- Position du cube dans le repère CAMÉRA ---")
    print(f"  X (gauche/droite):  {position[0]:+.4f} m")
    print(f"  Y (haut/bas):       {position[1]:+.4f} m")
    print(f"  Z (profondeur):     {position[2]:+.4f} m")
    print(f"  Distance:           {np.linalg.norm(position):.4f} m")

    return {
        'position_camera_frame': position,
        'rvec': rvec,
        'tvec': tvec,
        'corners': corners,
        'ids': ids
    }


# Generated by GitHub Copilot
def draw_pose_on_image(image, pose_result, camera_matrix, distortion_coeff, marker_size_m=0.08):
    """
    Draw the detected marker, its axes 3D et la distance sur l'image.

    Args:
        image: Image BGR à annoter (copie réalisée en interne)
        pose_result: Résultat de estimate_cube_pose
        camera_matrix: Matrice intrinsèque K
        distortion_coeff: Coefficients de distorsion
        marker_size_m: Taille physique du marqueur en mètres

    Returns:
        Image annotée (BGR)
    """
    annotated = image.copy()  # Ne modifie pas l'image originale

    # Dessine les contours du marqueur détecté
    cv2.aruco.drawDetectedMarkers(annotated, pose_result['corners'], pose_result['ids'])

    # Dessine les axes 3D du repère du marqueur (rouge=X, vert=Y, bleu=Z)
    cv2.drawFrameAxes(annotated, camera_matrix, distortion_coeff,
                      pose_result['rvec'], pose_result['tvec'],
                      marker_size_m * 0.5)

    # Affiche la distance caméra-cube en overlay
    pos = pose_result['position_camera_frame']
    distance = np.linalg.norm(pos)
    label = f"Cube: ({pos[0]:+.3f}, {pos[1]:+.3f}, {pos[2]:+.3f}) m  |  dist={distance:.3f} m"

    # Positionne le texte en bas de l'image
    h, w = annotated.shape[:2]
    cv2.putText(annotated, label, (10, h - 15),
                cv2.FONT_HERSHEY_SIMPLEX, 0.55, (0, 255, 0), 2, cv2.LINE_AA)

    return annotated


# Generated by GitHub Copilot
def run_on_saved_image(image_path, calibration_dir, marker_size_m=0.08):
    """
    Charge une image existante et estime la position du cube.
    Utile pour tester sans caméra physique.
    """
    if not os.path.exists(image_path):
        raise FileNotFoundError(f"Image non trouvée: {image_path}")

    camera_matrix, distortion_coeff = load_calibration(calibration_dir)

    image = cv2.imread(image_path)
    if image is None:
        raise ValueError(f"Impossible de lire: {image_path}")

    try:
        pose = estimate_cube_pose(image, camera_matrix, distortion_coeff, marker_size_m)

        if pose is not None:
            annotated = draw_pose_on_image(image, pose, camera_matrix, distortion_coeff, marker_size_m)

            # Sauvegarde l'image annotée
            output_path = os.path.join(os.path.dirname(image_path), 'pose_estimation_result.png')
            cv2.imwrite(output_path, annotated)
            print(f"\n✓ Image annotée sauvegardée: {output_path}")

            return pose
    finally:
        del image  # Libération explicite de la mémoire

    return None


if __name__ == "__main__":
    # Generated by GitHub Copilot
    ARUCO_DIR = os.path.dirname(os.path.abspath(__file__))
    ROBOT_DIR = os.path.dirname(ARUCO_DIR)

    # D'abord, régénère les fichiers de calibration si absents
    CALIBRATION_DIR = ROBOT_DIR
    camera_matrix_path = os.path.join(CALIBRATION_DIR, 'camera_matrix.npy')

    if not os.path.exists(camera_matrix_path):
        print("Fichiers de calibration absents — relance la calibration...")
        from aruco import calibrate_camera
        cam_mat, dist = calibrate_camera(
            os.path.join(ROBOT_DIR, 'marker_42.png'),
            os.path.join(ARUCO_DIR, 'aruco_scene.xml')
        )
        if cam_mat is not None:
            np.save(os.path.join(CALIBRATION_DIR, 'camera_matrix.npy'), cam_mat)
            np.save(os.path.join(CALIBRATION_DIR, 'distortion_coeff.npy'), dist)
            print("Calibration sauvegardee")

    IMAGE_PATH = os.path.join(ROBOT_DIR, 'marker_42.png')

    print("="*70)
    print("ESTIMATION DE LA POSITION DU CUBE (CAMÉRA MOBILE)")
    print("="*70)
    print()
    print("Principe:")
    print("  1. La matrice K (calibration) est FIXE — elle décrit l'optique de la caméra")
    print("  2. Quand la caméra bouge, K ne change pas")
    print("  3. solvePnP recalcule R et t (extrinsèques) à chaque nouvelle image")
    print("  4. tvec = position du cube dans le repère de la caméra")
    print()

    try:
        pose = run_on_saved_image(IMAGE_PATH, CALIBRATION_DIR)
    except Exception as e:
        print(f"✗ Erreur: {e}")
        import traceback
        traceback.print_exc()
