"""
Complete camera calibration and cube localization report.
Generates calibration results with visualization and summary.

Security: File paths validated. Scene loading includes error handling.
"""
import cv2
import numpy as np
import json
import os
import sys
from datetime import datetime

try:
    import mujoco
except ImportError:
    print("Warning: mujoco not installed. Install with: pip install mujoco")
    mujoco = None

# Generated by GitHub Copilot
def generate_calibration_report(calibration_results, output_dir):
    """
    Generate a complete calibration report with results and visualizations.
    
    Args:
        calibration_results: Dictionary with calibration data
        output_dir: Directory to save report
    """
    # Create report directory
    os.makedirs(output_dir, exist_ok=True)
    report_dir = os.path.join(output_dir, 'calibration_report')
    os.makedirs(report_dir, exist_ok=True)
    
    # Save camera matrix
    camera_matrix = calibration_results['camera_matrix']
    np.save(os.path.join(report_dir, 'camera_matrix.npy'), camera_matrix)
    
    # Save distortion coefficients
    distortion_coeff = calibration_results['distortion_coeff']
    np.save(os.path.join(report_dir, 'distortion_coeff.npy'), distortion_coeff)
    
    # Create JSON report
    cube_pos = calibration_results['cube_position']
    report_data = {
        'timestamp': datetime.now().isoformat(),
        'camera_parameters': {
            'focal_length_px': float(calibration_results['focal_length']),
            'camera_matrix': camera_matrix.tolist(),
            'distortion_coefficients': distortion_coeff.flatten().tolist(),
            'principal_point': [float(camera_matrix[0, 2]), float(camera_matrix[1, 2])]
        },
        'cube_localization': {
            'position_x_m': float(cube_pos[0]),
            'position_y_m': float(cube_pos[1]),
            'position_z_m': float(cube_pos[2]),
            'position_array': cube_pos.tolist()
        },
        'marker_information': {
            'marker_id': calibration_results['marker_id'],
            'marker_size_mm': calibration_results['marker_size_mm'],
            'dictionary': 'DICT_6X6_250'
        },
        'scene_information': {
            'camera_to_cube_distance_m': float(calibration_results['camera_to_cube_distance'])
        }
    }
    
    # Save JSON report
    report_path = os.path.join(report_dir, 'calibration_report.json')
    with open(report_path, 'w') as f:
        json.dump(report_data, f, indent=2)
    
    # Create text summary
    summary_path = os.path.join(report_dir, 'SUMMARY.txt')
    with open(summary_path, 'w') as f:
        f.write("=" * 70 + "\n")
        f.write("CAMERA CALIBRATION AND CUBE LOCALIZATION REPORT\n")
        f.write("=" * 70 + "\n\n")
        
        f.write("CAMERA PARAMETERS\n")
        f.write("-" * 70 + "\n")
        f.write(f"Estimated Focal Length: {calibration_results['focal_length']:.2f} pixels\n")
        f.write(f"Principal Point: ({camera_matrix[0, 2]:.1f}, {camera_matrix[1, 2]:.1f})\n")
        f.write(f"\nCamera Matrix:\n")
        for row in camera_matrix:
            f.write(f"  {row[0]:12.4f}  {row[1]:12.4f}  {row[2]:12.4f}\n")
        f.write(f"\nDistortion Coefficients: {distortion_coeff.flatten()}\n")
        
        f.write("\n" + "=" * 70 + "\n")
        f.write("CUBE LOCALIZATION\n")
        f.write("-" * 70 + "\n")
        f.write(f"X Position: {cube_pos[0]:.6f} m\n")
        f.write(f"Y Position: {cube_pos[1]:.6f} m\n")
        f.write(f"Z Position: {cube_pos[2]:.6f} m\n")
        f.write(f"Position Vector: {cube_pos}\n")
        
        f.write("\n" + "=" * 70 + "\n")
        f.write("MARKER INFORMATION\n")
        f.write("-" * 70 + "\n")
        f.write(f"Marker ID: {calibration_results['marker_id']}\n")
        f.write(f"Marker Size: {calibration_results['marker_size_mm']} mm\n")
        f.write(f"Dictionary: DICT_6X6_250 (6x6 ArUco)\n")
        
        f.write("\n" + "=" * 70 + "\n")
        f.write("SCENE GEOMETRY\n")
        f.write("-" * 70 + "\n")
        f.write(f"Camera to Cube Distance: {calibration_results['camera_to_cube_distance']:.3f} m\n")
        
        f.write("\n" + "=" * 70 + "\n")
        f.write(f"Report generated: {report_data['timestamp']}\n")
        f.write("=" * 70 + "\n")
    
    print(f"\n✓ Full report saved to: {report_dir}")
    print(f"  - calibration_report.json")
    print(f"  - SUMMARY.txt")
    print(f"  - camera_matrix.npy")
    print(f"  - distortion_coeff.npy")

if __name__ == "__main__":
    # Import the calibration function from the main script
    from calibrate_from_scene_box import calibrate_camera_from_scene

    # Generated by GitHub Copilot
    ARUCO_DIR = os.path.dirname(os.path.abspath(__file__))
    SCENE_PATH = os.path.join(ARUCO_DIR, 'scene_box_aruco.xml')
    OUTPUT_DIR = os.path.join(ARUCO_DIR, 'calibration_output')
    
    try:
        print("Starting camera calibration from MuJoCo scene...\n")
        results = calibrate_camera_from_scene(SCENE_PATH, output_dir=OUTPUT_DIR)
        
        if results:
            print("\n" + "=" * 70)
            generate_calibration_report(results, OUTPUT_DIR)
            print("=" * 70)
    except Exception as e:
        print(f"✗ Error: {e}")
        import traceback
        traceback.print_exc()
