"""
Real-time cube pose estimation from a webcam using an ArUco marker.

Usage:
  python live_cube_pose_webcam.py

Controls:
  q : quit
  o : flip cube offset sign (if cube center looks inverted)

Security: File paths and camera access are validated.
"""

import os
import cv2
import numpy as np


# Generated by GitHub Copilot
def load_intrinsics(robot_dir):
    """Load camera intrinsics from numpy files in project root."""
    k_path = os.path.join(robot_dir, "camera_matrix.npy")
    d_path = os.path.join(robot_dir, "distortion_coeff.npy")

    if not os.path.exists(k_path) or not os.path.exists(d_path):
        raise FileNotFoundError(
            "Missing camera calibration files. Expected camera_matrix.npy and "
            "distortion_coeff.npy in project root."
        )

    k = np.load(k_path)
    d = np.load(d_path)
    return k.astype(np.float32), d.astype(np.float32)


# Generated by GitHub Copilot
def estimate_marker_pose_solvepnp(corners_2d, camera_matrix, dist_coeff, marker_size_m):
    """Estimate marker pose from 2D corners using solvePnP."""
    half = marker_size_m / 2.0
    object_points = np.array(
        [
            [-half, half, 0.0],
            [half, half, 0.0],
            [half, -half, 0.0],
            [-half, -half, 0.0],
        ],
        dtype=np.float32,
    )

    ok, rvec, tvec = cv2.solvePnP(
        object_points,
        corners_2d.astype(np.float32),
        camera_matrix,
        dist_coeff,
        flags=cv2.SOLVEPNP_ITERATIVE,
    )
    if not ok:
        return None, None
    return rvec, tvec


# Generated by GitHub Copilot
def marker_to_cube_center_camera_frame(rvec, tvec, cube_offset_z_m):
    """
    Convert marker center pose to cube center in camera frame.

    cube_offset_z_m is expressed in marker frame.
    Example: -0.02 means cube center is 2 cm below marker plane along marker Z.
    """
    rot_m2c, _ = cv2.Rodrigues(rvec)
    offset_marker = np.array([[0.0], [0.0], [cube_offset_z_m]], dtype=np.float32)
    cube_center_c = tvec + rot_m2c @ offset_marker
    return cube_center_c.reshape(3)


# Generated by GitHub Copilot
def main():
    """Run live webcam loop and display cube position from ArUco marker."""
    # Generated by GitHub Copilot
    aruco_dir = os.path.dirname(os.path.abspath(__file__))
    robot_dir = os.path.dirname(aruco_dir)
    marker_id = 42
    marker_size_m = 0.08
    cube_offset_z_m = -0.02

    camera_matrix, dist_coeff = load_intrinsics(robot_dir)

    aruco_dict = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_6X6_250)
    params = cv2.aruco.DetectorParameters()
    detector = cv2.aruco.ArucoDetector(aruco_dict, params)

    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        raise RuntimeError("Cannot open webcam 0")

    print("Live cube pose started")
    print("- Marker dictionary: DICT_6X6_250")
    print(f"- Marker ID tracked: {marker_id}")
    print(f"- Marker size: {marker_size_m} m")
    print("Controls: q=quit, o=flip cube offset sign")

    try:
        while True:
            ok, frame = cap.read()
            if not ok:
                continue

            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            corners, ids, _ = detector.detectMarkers(gray)

            if ids is not None and len(ids) > 0:
                cv2.aruco.drawDetectedMarkers(frame, corners, ids)

                # Track the requested marker ID if present.
                for idx, detected_id in enumerate(ids.flatten()):
                    if int(detected_id) != marker_id:
                        continue

                    c2d = corners[idx][0]
                    rvec, tvec = estimate_marker_pose_solvepnp(
                        c2d, camera_matrix, dist_coeff, marker_size_m
                    )
                    if rvec is None:
                        continue

                    # Draw marker axes.
                    cv2.drawFrameAxes(
                        frame,
                        camera_matrix,
                        dist_coeff,
                        rvec,
                        tvec,
                        marker_size_m * 0.5,
                    )

                    cube_c = marker_to_cube_center_camera_frame(rvec, tvec, cube_offset_z_m)
                    dist_m = float(np.linalg.norm(cube_c))

                    line1 = (
                        f"cube_cam (m): x={cube_c[0]:+.3f} "
                        f"y={cube_c[1]:+.3f} z={cube_c[2]:+.3f}"
                    )
                    line2 = f"distance={dist_m:.3f} m | offset_z={cube_offset_z_m:+.3f}"

                    cv2.putText(
                        frame,
                        line1,
                        (12, 30),
                        cv2.FONT_HERSHEY_SIMPLEX,
                        0.6,
                        (0, 255, 0),
                        2,
                        cv2.LINE_AA,
                    )
                    cv2.putText(
                        frame,
                        line2,
                        (12, 58),
                        cv2.FONT_HERSHEY_SIMPLEX,
                        0.6,
                        (0, 255, 0),
                        2,
                        cv2.LINE_AA,
                    )

                    # Log one-line state in terminal for debugging.
                    print(
                        f"ID {marker_id} | cube_cam=({cube_c[0]:+.3f},"
                        f"{cube_c[1]:+.3f},{cube_c[2]:+.3f}) m | d={dist_m:.3f}"
                    )
                    break

            cv2.imshow("Live Cube Pose (ArUco)", frame)
            key = cv2.waitKey(1) & 0xFF

            if key == ord("q"):
                break
            if key == ord("o"):
                cube_offset_z_m *= -1.0
                print(f"Offset flipped. cube_offset_z_m={cube_offset_z_m:+.3f} m")

    finally:
        cap.release()
        cv2.destroyAllWindows()


if __name__ == "__main__":
    main()
