# Generated by GitHub Copilot
"""Run SmolVLA from Hugging Face in SO100 MuJoCo simulation with live rendering.

Usage examples:
  mjpython ARUCO/run_smolvla_live_sim.py
  mjpython ARUCO/run_smolvla_live_sim.py --model-id masato-ka/smolvla_block_instruction --task pick_place
  mjpython ARUCO/run_smolvla_live_sim.py --instruction "pick the block" --steps 300
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np
import torch


# Generated by GitHub Copilot
def add_repo_paths(repo_root: Path) -> None:
    """Add local project paths so LeRobot and SO100 env modules can be imported."""
    paths = [
        repo_root,
        repo_root / "lerobot" / "src",
        repo_root / "AA-UNUSED",
    ]
    for path in paths:
        path_str = str(path)
        if path_str not in sys.path:
            sys.path.insert(0, path_str)


# Generated by GitHub Copilot
def parse_args() -> argparse.Namespace:
    """Parse CLI arguments for live SmolVLA simulation."""
    parser = argparse.ArgumentParser(description="Run SmolVLA live in SO100 MuJoCo simulation")
    parser.add_argument("--model-id", type=str, default="masato-ka/smolvla_block_instruction")
    parser.add_argument("--task", type=str, default="pick_place", choices=["reach", "pick", "pick_place"])
    parser.add_argument("--instruction", type=str, default="pick the block and place it in the goal")
    parser.add_argument("--episodes", type=int, default=1)
    parser.add_argument("--steps", type=int, default=400)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--render", action="store_true", default=True)
    parser.add_argument("--no-render", action="store_true")
    parser.add_argument("--frame-skip", type=int, default=8)
    parser.add_argument("--control-dt", type=float, default=0.04)
    parser.add_argument("--random-reset", action="store_true")
    parser.add_argument("--assist-grasp", action="store_true", default=True)
    parser.add_argument("--no-assist-grasp", action="store_true")
    parser.add_argument("--action-space", type=str, default="normalized", choices=["normalized", "pwm"],
                        help="Action space: 'normalized' [-1,1] or 'pwm' (real robot servo values)")
    return parser.parse_args()


# Generated by GitHub Copilot
def choose_device() -> torch.device:
    """Choose MPS on macOS when available, otherwise CPU."""
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


# Generated by GitHub Copilot
def get_feature_keys(policy: Any) -> tuple[str, str | None]:
    """Resolve image and optional state feature keys from policy config."""
    image_keys = list(policy.config.image_features.keys())
    if len(image_keys) == 0:
        raise RuntimeError("No image feature declared in model config.")

    image_key = image_keys[0]

    state_key = None
    for key in policy.config.input_features.keys():
        if "state" in key:
            state_key = key
            break

    return image_key, state_key


# Generated by GitHub Copilot
def make_processors_with_fallback(policy: Any, model_id: str, device: torch.device) -> tuple[Any, Any]:
    """Build pre/post processors, with fallback when processor JSON files are missing on HF."""
    from lerobot.policies.factory import make_pre_post_processors

    try:
        return make_pre_post_processors(
            policy.config,
            model_id,
            preprocessor_overrides={"device_processor": {"device": str(device)}},
        )
    except FileNotFoundError as exc:
        print(
            "[WARN] Missing processor config files on HF repo "
            f"({exc}). Falling back to local processor construction from policy config."
        )
        return make_pre_post_processors(
            policy.config,
            preprocessor_overrides={"device_processor": {"device": str(device)}},
        )


# Generated by GitHub Copilot
def prepare_policy_input(
    image_rgb: np.ndarray,
    obs_vec: np.ndarray,
    instruction: str,
    image_key: str,
    state_key: str | None,
    policy: Any,
) -> dict[str, Any]:
    """Build a frame dict consumed by LeRobot preprocess pipeline."""
    frame: dict[str, Any] = {
        image_key: image_rgb,
        "task": instruction,
    }
    if state_key is not None:
        state_dim = int(policy.config.input_features[state_key].shape[0])
        obs = obs_vec.astype(np.float32).reshape(-1)
        if obs.shape[0] < state_dim:
            padded = np.zeros((state_dim,), dtype=np.float32)
            padded[: obs.shape[0]] = obs
            obs = padded
        elif obs.shape[0] > state_dim:
            obs = obs[:state_dim]
        frame[state_key] = obs
    return frame


# Generated by GitHub Copilot
# Real SO100 robot PWM limits (servo positions from physical hardware)
PWM_LIMITS = np.array([
    [909, 3229],      # shoulder_pan
    [819, 3217],      # shoulder_lift
    [867, 3104],      # elbow_flex
    [842, 3201],      # wrist_flex
    [260, 3880],      # wrist_roll
    [2044, 3532],     # gripper
], dtype=np.float32)

# Simulation SO100 joint limits (in radians) - DENORMALIZATION TARGET
RAD_LIMITS = np.array([
    [-1.92, 1.92],    # motor 0 (shoulder_pan)
    [-3.32, 0.174],   # motor 1 (shoulder_lift)
    [-0.174, 3.14],   # motor 2 (elbow_flex)
    [-1.66, 1.66],    # motor 3 (wrist_flex)
    [-2.79, 2.79],    # motor 4 (wrist_roll)
    [-0.174, 1.75],   # motor 5 (gripper)
], dtype=np.float32)


# Generated by GitHub Copilot
def denormalize_action(action_normalized: np.ndarray) -> np.ndarray:
    """Convert normalized action [-1, 1] to joint angles in radians.
    
    Maps normalized values to simulation joint limits:
    -1 -> min angle for that joint
    +1 -> max angle for that joint
    
    Args:
        action_normalized: 7D array in [-1, 1] range
                          (6 joints + 1 gripper)
    
    Returns:
        7D array with joint angles in radians, clipped to valid ranges
    """
    action_rad = np.zeros(7, dtype=np.float32)
    rad_ranges = RAD_LIMITS[:, 1] - RAD_LIMITS[:, 0]
    rad_centers = (RAD_LIMITS[:, 0] + RAD_LIMITS[:, 1]) / 2.0
    
    for i in range(min(6, len(action_normalized))):
        # Denormalize: map [-1, 1] to [min, max] for joint i
        action_rad[i] = rad_centers[i] + (action_normalized[i] * rad_ranges[i] / 2.0)
        action_rad[i] = np.clip(action_rad[i], RAD_LIMITS[i, 0], RAD_LIMITS[i, 1])
    
    # Gripper: keep last dimension normalized [-1, 1] (usually handled separately)
    if len(action_normalized) > 6:
        action_rad[6] = np.clip(action_normalized[6], -1.0, 1.0)
    
    return action_rad


# Generated by GitHub Copilot
def pwm_to_radians(action_pwm: np.ndarray) -> np.ndarray:
    """Convert SO100 action from PWM servo space to simulation radian space.
    
    Maps real robot PWM servo positions to simulation joint angles.
    Real robot: PWM values (e.g., 909-3229 for shoulder_pan)
    Simulation: radian values (e.g., -1.92 to 1.92 for motor 0)
    
    Args:
        action_pwm: 6D array of PWM values (per-joint servo positions)
    
    Returns:
        6D array of radian values clipped to simulation limits
    """
    action_rad = np.zeros(6, dtype=np.float32)
    pwm_ranges = PWM_LIMITS[:, 1] - PWM_LIMITS[:, 0]
    rad_ranges = RAD_LIMITS[:, 1] - RAD_LIMITS[:, 0]
    
    for i in range(min(6, len(action_pwm))):
        # Normalize PWM to [0, 1]
        pwm_norm = (action_pwm[i] - PWM_LIMITS[i, 0]) / pwm_ranges[i]
        pwm_norm = np.clip(pwm_norm, 0.0, 1.0)
        
        # Scale to radian range
        action_rad[i] = RAD_LIMITS[i, 0] + pwm_norm * rad_ranges[i]
    
    return np.clip(action_rad, RAD_LIMITS[:, 0], RAD_LIMITS[:, 1]).astype(np.float32)


# Generated by GitHub Copilot
def adapt_action(action_tensor: torch.Tensor, target_dim: int = 7, action_space: str = "normalized") -> np.ndarray:
    """Convert policy action tensor to joint angles for the simulation environment.
    
    Args:
        action_tensor: Output from policy.select_action() in [-1, 1] range
        target_dim: Target action dimension (7 for SO100: 6 joints + 1 gripper)
        action_space: Either "normalized" ([-1,1] → denormalize to radians)
                      or "pwm" (PWM values → convert to radians)
    
    Returns:
        7D array with joint angles in radians, properly scaled to simulation limits
    """
    action = action_tensor.detach().float().cpu().numpy().reshape(-1)

    # Pad or truncate to target dimension
    if action.shape[0] < target_dim:
        padded = np.zeros((target_dim,), dtype=np.float32)
        padded[: action.shape[0]] = action
        action = padded
    elif action.shape[0] > target_dim:
        action = action[:target_dim]

    # Handle NaN/inf values
    action = np.nan_to_num(action, nan=0.0, posinf=1.0, neginf=-1.0)
    
    # Denormalize based on action space
    if action_space == "pwm":
        # Convert first 6 joints from PWM to radians, keep gripper normalized
        action_rad = np.zeros(target_dim, dtype=np.float32)
        action_rad[:6] = pwm_to_radians(action[:6])
        action_rad[6] = np.clip(action[6], -1.0, 1.0)
        return action_rad
    else:
        # Default: denormalize from [-1, 1] to radian ranges
        return denormalize_action(action)


# Generated by GitHub Copilot
def ensure_smolvla_batch_shapes(
    batch: dict[str, Any], image_key: str, state_key: str | None, device: torch.device
) -> dict[str, Any]:
    """Force batch tensors to SmolVLA runtime expectations (image BCHW, state BxD).
    
    Handles multiple image keys (e.g., observation.images.top, observation.images.wrist).
    """
    if image_key not in batch:
        raise RuntimeError(f"Missing primary image key in batch: {image_key}")

    # Process ALL image keys in the batch (not just the primary one)
    image_keys = [k for k in batch.keys() if "images" in k and isinstance(batch[k], (np.ndarray, torch.Tensor))]
    
    for img_key in image_keys:
        img = batch[img_key]
        if not torch.is_tensor(img):
            img = torch.as_tensor(img)

        # Accept HWC, BHWC, BCHW and convert to BCHW float32 in [0,1].
        if img.ndim == 3:  # HWC
            img = img.permute(2, 0, 1).unsqueeze(0)
        elif img.ndim == 4:
            # If last dim is channel, assume BHWC.
            if img.shape[-1] in (1, 3):
                img = img.permute(0, 3, 1, 2)
        else:
            raise RuntimeError(f"Unsupported image tensor shape for SmolVLA: {tuple(img.shape)}")

        img = img.contiguous().to(device=device, dtype=torch.float32)
        if torch.max(img) > 1.0:
            img = img / 255.0
        batch[img_key] = img

    if state_key is not None and state_key in batch:
        state = batch[state_key]
        if not torch.is_tensor(state):
            state = torch.as_tensor(state)
        if state.ndim == 1:
            state = state.unsqueeze(0)
        state = state.contiguous().to(device=device, dtype=torch.float32)
        batch[state_key] = state

    return batch


# Generated by GitHub Copilot
def main() -> None:
    """Load SmolVLA and run live simulation episodes in SO100 env."""
    args = parse_args()

    if args.no_render:
        args.render = False
    if args.no_assist_grasp:
        args.assist_grasp = False

    aruco_dir = Path(__file__).resolve().parent
    repo_root = aruco_dir.parent
    add_repo_paths(repo_root)

    from lerobot.policies.smolvla.modeling_smolvla import SmolVLAPolicy
    from so100_rl.so100_pick_place_env import SO100PickPlaceEnv
    import mujoco.viewer

    device = choose_device()
    print(f"[INFO] Device: {device}")
    print(f"[INFO] Loading model: {args.model_id}")

    policy = SmolVLAPolicy.from_pretrained(args.model_id).to(device).eval()
    preprocess, postprocess = make_processors_with_fallback(policy, args.model_id, device)

    image_key, state_key = get_feature_keys(policy)
    print(f"[INFO] Policy image key: {image_key}")
    print(f"[INFO] Policy state key: {state_key}")

    scene_path = repo_root / "SIMULATION" / "mujoco_menagerie" / "trs_so_arm100" / "scene_pick_place.xml"
    # Keep rgb_array always enabled for policy vision input.
    render_mode = "rgb_array"

    env = SO100PickPlaceEnv(
        scene_path=scene_path,
        task=args.task,
        render_mode=render_mode,
        max_episode_steps=args.steps,
        frame_skip=args.frame_skip,
        control_dt=args.control_dt,
        assist_grasp=args.assist_grasp,
        random_reset_pose=args.random_reset,
        seed=args.seed,
    )

    viewer = None
    if args.render:
        viewer = mujoco.viewer.launch_passive(env.model, env.data)

    try:
        for ep in range(args.episodes):
            obs, info = env.reset(seed=args.seed + ep)
            total_reward = 0.0
            start_t = time.time()
            print(f"\n[EP {ep + 1}/{args.episodes}] task={args.task} | instruction='{args.instruction}'")
            print(f"[EP {ep + 1}] reset info: {info}")

            for step in range(args.steps):
                img = env.render()
                if img is None:
                    raise RuntimeError(
                        "env.render() returned None. Use render mode enabled for live simulation."
                    )

                frame = prepare_policy_input(
                    image_rgb=img,
                    obs_vec=obs,
                    instruction=args.instruction,
                    image_key=image_key,
                    state_key=state_key,
                    policy=policy,
                )

                batch = preprocess(frame)
                batch = ensure_smolvla_batch_shapes(batch, image_key, state_key, device)

                with torch.inference_mode():
                    action = policy.select_action(batch)
                    action = postprocess(action)

                env_action = adapt_action(action, target_dim=env.action_space.shape[0], action_space=args.action_space)
                obs, reward, terminated, truncated, step_info = env.step(env_action)
                if viewer is not None:
                    viewer.sync()
                total_reward += float(reward)

                if step % 20 == 0:
                    print(
                        f"[EP {ep + 1}] step={step:03d} reward={reward:+.3f} "
                        f"success={bool(step_info.get('success', False))} "
                        f"action_norm={np.linalg.norm(env_action):.3f}"
                    )

                if terminated or truncated:
                    elapsed = time.time() - start_t
                    print(
                        f"[EP {ep + 1}] finished step={step + 1} "
                        f"terminated={terminated} truncated={truncated} "
                        f"success={bool(step_info.get('success', False))} "
                        f"total_reward={total_reward:.3f} elapsed={elapsed:.1f}s"
                    )
                    break

    finally:
        if viewer is not None:
            viewer.close()
        env.close()


if __name__ == "__main__":
    main()
