"""
Move a virtual camera around a fixed cube and verify cube localization stability.

This script does not move the cube. It only changes camera pose, estimates
marker pose with solvePnP, and reconstructs the cube world position to verify
that the estimated world position stays constant.

Security: Input files are validated before loading.
"""
import os
import xml.etree.ElementTree as ET

import cv2
import matplotlib.pyplot as plt
import numpy as np


# Generated by GitHub Copilot
def load_cube_center_from_scene(scene_path):
    """
    Read cube center position from MuJoCo scene XML.

    Args:
        scene_path: Absolute path to scene_box.xml.

    Returns:
        Numpy array [x, y, z] in meters.

    Raises:
        FileNotFoundError: If scene file is missing.
        ValueError: If cube body cannot be found or parsed.
    """
    if not os.path.exists(scene_path):
        raise FileNotFoundError(f"Scene file not found: {scene_path}")

    root = ET.parse(scene_path).getroot()
    worldbody = root.find("worldbody")
    if worldbody is None:
        raise ValueError("Missing <worldbody> in scene XML")

    cube_body = worldbody.find(".//body[@name='object']")
    if cube_body is None:
        raise ValueError("Missing cube body <body name='object'> in scene XML")

    pos_str = cube_body.get("pos", "")
    parts = pos_str.split()
    if len(parts) != 3:
        raise ValueError(f"Invalid cube pos format: {pos_str}")

    return np.array([float(parts[0]), float(parts[1]), float(parts[2])], dtype=np.float64)


# Generated by GitHub Copilot
def load_or_build_camera_intrinsics(robot_dir):
    """
    Load camera intrinsics from .npy files, or generate from aruco.py fallback.

    Args:
        robot_dir: Project root path.

    Returns:
        Tuple (K, dist) where K is 3x3 intrinsic matrix and dist is distortion vector.
    """
    k_path = os.path.join(robot_dir, "camera_matrix.npy")
    d_path = os.path.join(robot_dir, "distortion_coeff.npy")

    if os.path.exists(k_path) and os.path.exists(d_path):
        return np.load(k_path), np.load(d_path)

    from aruco import calibrate_camera

    image_path = os.path.join(robot_dir, "marker_42.png")
    scene_path = os.path.join(robot_dir, "aruco_scene.xml")
    camera_matrix, distortion_coeff = calibrate_camera(image_path, scene_path)
    if camera_matrix is None:
        raise ValueError("Failed to build camera intrinsics from fallback calibration")

    np.save(k_path, camera_matrix)
    np.save(d_path, distortion_coeff)
    return camera_matrix, distortion_coeff


# Generated by GitHub Copilot
def make_lookat_extrinsics(camera_pos_w, target_w, world_up=np.array([0.0, 0.0, 1.0])):
    """
    Build world->camera extrinsics for a look-at camera.

    Camera convention is OpenCV-like (x right, y down, z forward).

    Args:
        camera_pos_w: Camera center in world frame (3,).
        target_w: Look-at target in world frame (3,).
        world_up: Up direction in world frame.

    Returns:
        Tuple (R_cw, t_cw, R_wc) where:
        - R_cw: world->camera rotation (3x3)
        - t_cw: world->camera translation (3x1)
        - R_wc: camera->world rotation (3x3)
    """
    z_cam_w = target_w - camera_pos_w
    z_cam_w = z_cam_w / np.linalg.norm(z_cam_w)

    x_cam_w = np.cross(z_cam_w, world_up)
    x_cam_w = x_cam_w / np.linalg.norm(x_cam_w)

    y_cam_w = np.cross(z_cam_w, x_cam_w)
    y_cam_w = y_cam_w / np.linalg.norm(y_cam_w)

    # Columns are camera basis vectors expressed in world frame.
    R_wc = np.column_stack((x_cam_w, y_cam_w, z_cam_w))
    R_cw = R_wc.T
    t_cw = -R_cw @ camera_pos_w.reshape(3, 1)

    return R_cw, t_cw, R_wc


# Generated by GitHub Copilot
def simulate_and_estimate_fixed_cube(scene_path, K, dist, marker_size_m=0.08, num_views=12):
    """
    Simulate camera motion around a fixed cube and estimate cube world position.

    Args:
        scene_path: MuJoCo scene path for cube reference position.
        K: Camera intrinsic matrix.
        dist: Distortion coefficients.
        marker_size_m: ArUco marker size on cube (meters).
        num_views: Number of camera viewpoints.

    Returns:
        List of per-view dictionaries with true and estimated positions/errors.
    """
    cube_center_w = load_cube_center_from_scene(scene_path)

    # Cube is 4 cm side in scene_box.xml (geom size 0.02 => full side 0.04).
    # Marker center assumed at top face center.
    cube_half_height = 0.02
    marker_center_w = cube_center_w + np.array([0.0, 0.0, cube_half_height], dtype=np.float64)

    half = marker_size_m / 2.0
    # Marker local 3D corners (z=0 plane, center origin).
    obj_pts_local = np.array([
        [-half, half, 0.0],
        [half, half, 0.0],
        [half, -half, 0.0],
        [-half, -half, 0.0],
    ], dtype=np.float64)

    # Marker orientation in world: lying flat on top face (normal +Z).
    R_mw = np.eye(3)
    world_pts = (R_mw @ obj_pts_local.T).T + marker_center_w

    target = marker_center_w.copy()
    radius = 0.65
    base_z = 0.42

    results = []

    for i in range(num_views):
        theta = (2.0 * np.pi * i) / num_views
        cam_pos = np.array([
            cube_center_w[0] + radius * np.cos(theta),
            cube_center_w[1] + radius * np.sin(theta),
            base_z + 0.05 * np.sin(2.0 * theta),
        ], dtype=np.float64)

        R_cw, t_cw, R_wc = make_lookat_extrinsics(cam_pos, target)

        # Project marker corners to image plane using ground-truth camera pose.
        rvec_gt, _ = cv2.Rodrigues(R_cw)
        img_pts, _ = cv2.projectPoints(world_pts, rvec_gt, t_cw, K, dist)
        img_pts = img_pts.reshape(-1, 2).astype(np.float64)

        # Estimate marker pose from synthetic 2D points.
        ok, rvec_est, tvec_est = cv2.solvePnP(
            obj_pts_local.astype(np.float32),
            img_pts.astype(np.float32),
            K,
            dist,
            flags=cv2.SOLVEPNP_ITERATIVE,
        )
        if not ok:
            continue

        # Marker center in camera frame is tvec_est.
        marker_center_c = tvec_est.reshape(3)

        # Convert estimated marker center back to world frame.
        marker_center_w_est = (R_wc @ marker_center_c.reshape(3, 1)).reshape(3) + cam_pos

        # Convert marker center to cube center (marker on top face).
        cube_center_w_est = marker_center_w_est - np.array([0.0, 0.0, cube_half_height], dtype=np.float64)

        err = np.linalg.norm(cube_center_w_est - cube_center_w)

        results.append(
            {
                "view": i,
                "camera_pos_w": cam_pos,
                "cube_true_w": cube_center_w,
                "cube_est_w": cube_center_w_est,
                "cube_in_camera_frame": marker_center_c,
                "img_pts": img_pts,
                "rvec_est": rvec_est,
                "tvec_est": tvec_est,
                "error_m": err,
            }
        )

    return results


# Generated by GitHub Copilot
def plot_simulation_results(results, save_path):
    """
    Plot simulation overview in world frame and per-view error trend.

    Args:
        results: List returned by simulate_and_estimate_fixed_cube.
        save_path: Output image path.
    """
    cam = np.array([r["camera_pos_w"] for r in results])
    est = np.array([r["cube_est_w"] for r in results])
    true = np.array([r["cube_true_w"] for r in results])
    err = np.array([r["error_m"] for r in results])
    views = np.array([r["view"] for r in results])

    fig = plt.figure(figsize=(12, 6))

    ax1 = fig.add_subplot(1, 2, 1, projection="3d")
    ax1.plot(cam[:, 0], cam[:, 1], cam[:, 2], "o-", color="tab:blue", label="camera path")
    ax1.scatter(true[0, 0], true[0, 1], true[0, 2], s=120, color="tab:green", label="cube true")
    ax1.scatter(est[:, 0], est[:, 1], est[:, 2], s=30, color="tab:red", label="cube estimated")
    ax1.set_title("Simulation in world frame")
    ax1.set_xlabel("X (m)")
    ax1.set_ylabel("Y (m)")
    ax1.set_zlabel("Z (m)")
    ax1.legend(loc="best")

    ax2 = fig.add_subplot(1, 2, 2)
    ax2.plot(views, err, "o-", color="tab:purple")
    ax2.set_title("Estimation error by view")
    ax2.set_xlabel("View index")
    ax2.set_ylabel("Error (m)")
    ax2.grid(True, alpha=0.3)

    fig.tight_layout()
    fig.savefig(save_path, dpi=150)
    plt.close(fig)


# Generated by GitHub Copilot
def render_simulated_view_image(result, K, dist, marker_size_m=0.08, width=640, height=480):
    """
    Render one synthetic camera image with marker outline, axes, and coordinates.

    Args:
        result: One result item from simulate_and_estimate_fixed_cube.
        K: Camera intrinsic matrix.
        dist: Distortion coefficients.
        marker_size_m: Marker size used to draw frame axes.
        width: Output image width.
        height: Output image height.

    Returns:
        Annotated BGR image.
    """
    img = np.full((height, width, 3), 245, dtype=np.uint8)

    # Draw marker polygon and corner points.
    pts = np.round(result["img_pts"]).astype(np.int32)
    cv2.polylines(img, [pts], isClosed=True, color=(20, 20, 20), thickness=2)
    for p in pts:
        cv2.circle(img, tuple(p), 4, (0, 120, 255), -1)

    # Draw estimated marker frame axes.
    cv2.drawFrameAxes(
        img,
        K,
        dist,
        result["rvec_est"],
        result["tvec_est"],
        marker_size_m * 0.5,
    )

    # Write coordinates and error directly on each view image.
    t = result["cube_true_w"]
    e = result["cube_est_w"]
    c = result["cube_in_camera_frame"]
    err = result["error_m"]

    cv2.putText(
        img,
        f"view {result['view']:02d}",
        (12, 24),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.65,
        (30, 30, 30),
        2,
        cv2.LINE_AA,
    )
    cv2.putText(
        img,
        f"true_w: ({t[0]:+.3f}, {t[1]:+.3f}, {t[2]:+.3f}) m",
        (12, height - 74),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.47,
        (0, 110, 0),
        1,
        cv2.LINE_AA,
    )
    cv2.putText(
        img,
        f"est_w:  ({e[0]:+.3f}, {e[1]:+.3f}, {e[2]:+.3f}) m",
        (12, height - 54),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.47,
        (0, 0, 180),
        1,
        cv2.LINE_AA,
    )
    cv2.putText(
        img,
        f"cube_cam:({c[0]:+.3f}, {c[1]:+.3f}, {c[2]:+.3f}) m",
        (12, height - 34),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.47,
        (140, 0, 120),
        1,
        cv2.LINE_AA,
    )
    cv2.putText(
        img,
        f"err={err:.2e} m",
        (12, height - 14),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.47,
        (30, 30, 30),
        1,
        cv2.LINE_AA,
    )

    return img


# Generated by GitHub Copilot
def save_simulated_views_grid(results, K, dist, save_path, marker_size_m=0.08):
    """
    Save a grid of simulated camera images with overlaid coordinates per view.

    Args:
        results: List returned by simulate_and_estimate_fixed_cube.
        K: Camera intrinsic matrix.
        dist: Distortion coefficients.
        save_path: Output path for the grid image.
        marker_size_m: Marker size used for axis drawing.
    """
    selected = results[:8] if len(results) >= 8 else results
    if not selected:
        return

    cols = 4
    rows = int(np.ceil(len(selected) / cols))
    fig, axes = plt.subplots(rows, cols, figsize=(16, 4 * rows))
    axes = np.array(axes).reshape(rows, cols)

    for idx, r in enumerate(selected):
        rr = idx // cols
        cc = idx % cols
        bgr = render_simulated_view_image(r, K, dist, marker_size_m=marker_size_m)
        rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
        axes[rr, cc].imshow(rgb)
        axes[rr, cc].axis("off")

    for idx in range(len(selected), rows * cols):
        rr = idx // cols
        cc = idx % cols
        axes[rr, cc].axis("off")

    fig.suptitle("Simulated camera images with coordinates", fontsize=14)
    fig.tight_layout()
    fig.savefig(save_path, dpi=150)
    plt.close(fig)


# Generated by GitHub Copilot
def main():
    """Run a short camera-motion verification for fixed-cube pose estimation."""
    # Generated by GitHub Copilot
    aruco_dir = os.path.dirname(os.path.abspath(__file__))
    robot_dir = os.path.dirname(aruco_dir)
    scene_path = os.path.join(aruco_dir, "scene_box_aruco.xml")

    K, dist = load_or_build_camera_intrinsics(robot_dir)

    print("=" * 72)
    print("TEST: Camera motion with fixed cube")
    print("- Cube remains fixed in world frame")
    print("- Camera moves around cube")
    print("- solvePnP estimates marker pose each view")
    print("- Reconstructed cube world position should stay constant")
    print("=" * 72)

    results = simulate_and_estimate_fixed_cube(scene_path, K, dist, marker_size_m=0.08, num_views=16)
    if not results:
        print("No valid views were estimated.")
        return

    print("\nPer-view results:")
    for r in results:
        c = r["camera_pos_w"]
        t = r["cube_true_w"]
        e = r["cube_est_w"]
        cc = r["cube_in_camera_frame"]
        d = e - t
        print(
            f"view {r['view']:02d} | cam=({c[0]:+.3f},{c[1]:+.3f},{c[2]:+.3f}) "
            f"| cube_true_w=({t[0]:+.4f},{t[1]:+.4f},{t[2]:+.4f}) "
            f"| cube_est_w=({e[0]:+.4f},{e[1]:+.4f},{e[2]:+.4f}) "
            f"| delta=({d[0]:+.4e},{d[1]:+.4e},{d[2]:+.4e}) "
            f"| cube_cam=({cc[0]:+.4f},{cc[1]:+.4f},{cc[2]:+.4f}) "
            f"| err={r['error_m']:.6f} m"
        )

    errors = np.array([r["error_m"] for r in results])
    print("\nSummary:")
    print(f"  views used: {len(results)}")
    print(f"  mean world-position error: {errors.mean():.6f} m")
    print(f"  max  world-position error: {errors.max():.6f} m")
    print("\nExpected behavior:")
    print("  - cube_est_w should stay almost constant")
    print("  - cube_cam should change as camera moves")

    sim_path = os.path.join(aruco_dir, "simulation_cube_pose.png")
    plot_simulation_results(results, sim_path)
    print(f"\nSimulation figure saved: {sim_path}")

    views_path = os.path.join(aruco_dir, "simulation_views_with_coords.png")
    save_simulated_views_grid(results, K, dist, views_path, marker_size_m=0.08)
    print(f"Simulation views saved: {views_path}")


if __name__ == "__main__":
    main()
