"""
Test XML parsing without window display.
"""
import xml.etree.ElementTree as ET
import os

# Generated by GitHub Copilot
ARUCO_DIR = os.path.dirname(os.path.abspath(__file__))
scene_path = os.path.join(ARUCO_DIR, 'aruco_scene.xml')

try:
    tree = ET.parse(scene_path)
    root = tree.getroot()
    calib_elem = root.find('calibration')
    
    marker_size = calib_elem.find('marker_size_mm')
    distance = calib_elem.find('expected_distance_m')
    
    print("✓ XML parsed successfully!")
    print(f"Marker size (mm): {marker_size.text}")
    print(f"Expected distance (m): {distance.text}")
    
except Exception as e:
    print(f"✗ Error: {e}")
