"""
Visualize the robot scene with cube and ArUco marker.
Shows the scene layout for camera calibration setup.

Security: File paths are validated. XML parsing includes error handling.
"""
import xml.etree.ElementTree as ET
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import numpy as np
import os

# Generated by GitHub Copilot
def visualize_scene(scene_path):
  """
  Visualize the 3D scene from XML configuration.
  
  Args:
    scene_path: Path to scene XML file
  """
  if not os.path.exists(scene_path):
    raise FileNotFoundError(f"Scene file not found: {scene_path}")
  
  tree = ET.parse(scene_path)
  root = tree.getroot()
  
  fig = plt.figure(figsize=(12, 10))
  ax = fig.add_subplot(111, projection='3d')
  
  # Camera position
  camera = root.find('camera')
  if camera is not None:
    cam_pos = camera.find('position')
    cam_x = float(cam_pos.get('x'))
    cam_y = float(cam_pos.get('y'))
    cam_z = float(cam_pos.get('z'))
    ax.scatter([cam_x], [cam_y], [cam_z], c='red', marker='o', s=200, label='Camera')
    ax.text(cam_x, cam_y, cam_z + 0.05, 'Camera', fontsize=10)
  
  # Objects
  for obj in root.findall('object'):
    obj_id = obj.get('id')
    obj_type = obj.get('type')
    pos = obj.find('position')
    
    if pos is not None:
      x = float(pos.get('x'))
      y = float(pos.get('y'))
      z = float(pos.get('z'))
      
      if obj_type == 'box':
        dims = obj.find('dimensions')
        width = float(dims.get('width'))
        height = float(dims.get('height'))
        depth = float(dims.get('depth'))
        
        # Draw cube
        vertices = np.array([
          [x - width/2, y - height/2, z - depth/2],
          [x + width/2, y - height/2, z - depth/2],
          [x + width/2, y + height/2, z - depth/2],
          [x - width/2, y + height/2, z - depth/2],
          [x - width/2, y - height/2, z + depth/2],
          [x + width/2, y - height/2, z + depth/2],
          [x + width/2, y + height/2, z + depth/2],
          [x - width/2, y + height/2, z + depth/2],
        ])
        
        faces = [
          [vertices[0], vertices[1], vertices[5], vertices[4]],
          [vertices[7], vertices[6], vertices[2], vertices[3]],
          [vertices[0], vertices[3], vertices[7], vertices[4]],
          [vertices[1], vertices[2], vertices[6], vertices[5]],
          [vertices[0], vertices[1], vertices[2], vertices[3]],
          [vertices[4], vertices[5], vertices[6], vertices[7]],
        ]
        
        cube = Poly3DCollection(faces, alpha=0.6, linewidths=1, edgecolors='gray', facecolor='cyan')
        ax.add_collection3d(cube)
        ax.scatter([x], [y], [z], c='cyan', marker='s', s=100, label='Cube')
        ax.text(x, y, z + 0.08, obj_id, fontsize=10)
      
      elif obj_type == 'robot':
        ax.scatter([x], [y], [z], c='green', marker='^', s=200, label='Robot')
        ax.text(x, y, z + 0.05, obj_id, fontsize=10)
  
  # Lighting
  ax.set_xlabel('X (m)')
  ax.set_ylabel('Y (m)')
  ax.set_zlabel('Z (m)')
  ax.set_title('Robot Scene with Camera Calibration Setup', fontsize=14, fontweight='bold')
  
  # Set equal aspect ratio
  max_range = 0.6
  ax.set_xlim([0 - max_range/2, max_range])
  ax.set_ylim([0 - max_range/2, max_range])
  ax.set_zlim([0, max_range])
  
  ax.legend(loc='upper right')
  ax.grid(True, alpha=0.3)
  
  plt.tight_layout()
  
  # Save and show
  output_path = os.path.join(os.path.dirname(scene_path), 'scene_visualization.png')
  plt.savefig(output_path, dpi=150, bbox_inches='tight')
  print(f"✓ Scene visualization saved to: {output_path}")
  plt.show()

if __name__ == "__main__":
  # Generated by GitHub Copilot
  aruco_dir = os.path.dirname(os.path.abspath(__file__))
  scene_path = os.path.join(aruco_dir, 'aruco_scene.xml')
  
  try:
    visualize_scene(scene_path)
  except (FileNotFoundError, ET.ParseError) as e:
    print(f"Error: {e}")
