#!/usr/bin/env python3
# Generated by GithubCopilot
"""
Diagnostic de connexion SO-100
Vérifie : ports série disponibles, import lerobot, connexion bus,
calibration, lecture des positions moteurs.
"""

import sys
import os
import time


# ── Chemin vers lerobot (sans pip install) ────────────────────────────────────
_LEROBOT_SRC = os.path.join(os.path.dirname(__file__), "lerobot", "src")
if _LEROBOT_SRC not in sys.path:
    sys.path.insert(0, _LEROBOT_SRC)

# ── Configuration ─────────────────────────────────────────────────────────────
PORT = "/dev/tty.usbmodem59700734041"
ROBOT_ID = "so100_arm"

# ── Helpers ───────────────────────────────────────────────────────────────────
OK  = "✅"
NOK = "❌"
WARN = "⚠️ "
SEP = "─" * 60


def section(title: str) -> None:
    print(f"\n{SEP}\n  {title}\n{SEP}")


def result(label: str, ok: bool, detail: str = "") -> None:
    icon = OK if ok else NOK
    suffix = f"  ({detail})" if detail else ""
    print(f"  {icon}  {label}{suffix}")


# ═════════════════════════════════════════════════════════════════════════════
print("=" * 60)
print("  DIAGNOSTIC CONNEXION SO-100")
print("=" * 60)

# ── 1. Ports série disponibles ────────────────────────────────────────────────
section("1 · Ports série disponibles")
try:
    import serial.tools.list_ports
    ports = list(serial.tools.list_ports.comports())
    if ports:
        for p in ports:
            # Sur macOS tty.* et cu.* désignent le même device physique
            same_device = (p.device == PORT or
                           p.device == PORT.replace("/dev/tty.", "/dev/cu.") or
                           p.device == PORT.replace("/dev/cu.", "/dev/tty."))
            marker = " ◀ PORT CONFIGURÉ" if same_device else ""
            print(f"  • {p.device:45s} — {p.description}{marker}")
    else:
        print(f"  {WARN} Aucun port série trouvé")
    # Accepte /dev/tty.* et /dev/cu.* comme équivalents (macOS)
    port_found = (
        os.path.exists(PORT) or
        os.path.exists(PORT.replace("/dev/tty.", "/dev/cu.")) or
        any(p.device in (PORT, PORT.replace("/dev/tty.", "/dev/cu.")) for p in ports)
    )
    result(f"Port configuré présent  ({PORT})", port_found)
except ImportError:
    print(f"  {WARN} pyserial non installé — scan des ports ignoré")
    port_found = os.path.exists(PORT)
    result(f"Fichier device présent  ({PORT})", port_found)

if not port_found:
    print(f"\n  {NOK} Le robot ne semble pas branché sur {PORT}")
    print("       Vérifiez le câble USB et relancez.")
    sys.exit(1)

# ── 2. Imports lerobot ────────────────────────────────────────────────────────
section("2 · Imports lerobot")
try:
    import lerobot  # noqa: F401
    result("lerobot", True, lerobot.__file__)
except Exception as e:
    result("lerobot", False, str(e))
    sys.exit(1)

try:
    from lerobot.robots.so_follower.so_follower import SOFollower
    from lerobot.robots.so_follower.config_so_follower import SOFollowerRobotConfig
    result("SOFollower + SOFollowerRobotConfig", True)
except ImportError as e:
    result("SOFollower / SOFollowerRobotConfig", False, str(e))
    sys.exit(1)

# ── 3. Instanciation ──────────────────────────────────────────────────────────
section("3 · Instanciation du robot")
try:
    config = SOFollowerRobotConfig(port=PORT, id=ROBOT_ID)
    robot = SOFollower(config)
    result("SOFollower instancié", True, f"id={ROBOT_ID}")
except Exception as e:
    result("SOFollower instancié", False, str(e))
    sys.exit(1)

# ── 4. Connexion au bus ───────────────────────────────────────────────────────
section("4 · Connexion bus (serial → moteurs)")
print(f"  Port : {PORT}")
try:
    # calibrate=False pour éviter l'interaction interactive
    robot.connect(calibrate=False)
    result("robot.connect()", True)
except Exception as e:
    result("robot.connect()", False, str(e))
    sys.exit(1)

result("is_connected", robot.is_connected)

# ── 5. Calibration ────────────────────────────────────────────────────────────
section("5 · Calibration")
try:
    calibrated = robot.is_calibrated
    result("Calibration présente", calibrated,
           "OK" if calibrated else "lancez lerobot-calibrate pour calibrer")
except Exception as e:
    result("Lecture calibration", False, str(e))

# ── 6. Lecture des positions moteurs ─────────────────────────────────────────
section("6 · Positions moteurs (observation)")
try:
    obs = robot.get_observation()
    motors = {k: v for k, v in obs.items() if k.endswith(".pos")}
    if motors:
        col_w = max(len(k) for k in motors) + 2
        for name, val in motors.items():
            print(f"  • {name:{col_w}s} = {val:8.2f}°")
        result(f"{len(motors)} moteur(s) lus", True)
    else:
        print("  Aucun moteur .pos trouvé dans l'observation")
        result("Lecture moteurs", False)
except Exception as e:
    result("get_observation()", False, str(e))

# ── 7. Déconnexion ────────────────────────────────────────────────────────────
section("7 · Déconnexion")
try:
    robot.disconnect()
    result("robot.disconnect()", True)
except Exception as e:
    result("robot.disconnect()", False, str(e))

# ── Résumé ────────────────────────────────────────────────────────────────────
print(f"\n{'=' * 60}")
print(f"  {OK} Diagnostic terminé — le robot est bien connecté")
print(f"{'=' * 60}\n")
