#!/usr/bin/env python3
# Generated by GithubCopilot
"""
Séquence de mouvement SO-100
Enchaîne plusieurs poses sur les 6 articulations, puis revient
à la position de départ.

Moteurs  : shoulder_pan | shoulder_lift | elbow_flex
           wrist_flex   | wrist_roll    | gripper
Unité    : degrés  (use_degrees=True)  —  gripper en %  (0–100)
"""

import time
import sys
import os

# ── Chemin lerobot (sans pip install) ─────────────────────────────────────────
_LEROBOT_SRC = os.path.join(os.path.dirname(__file__), "lerobot", "src")
if _LEROBOT_SRC not in sys.path:
    sys.path.insert(0, _LEROBOT_SRC)

# ══════════════════════════════════════════════════════════════════════════════
#  CONFIGURATION
# ══════════════════════════════════════════════════════════════════════════════
PORT      = "/dev/tty.usbmodem59700734041"
ROBOT_ID  = "so100_arm"

STEPS    = 20     # nombre de sous-étapes par transition  (plus élevé = plus lisse)
STEP_HZ  = 20     # fréquence d'envoi des commandes (Hz)
PAUSE_S  = 1    # pause entre chaque pose (secondes)

# Séquence de poses — valeurs RELATIVES à la position initiale (degrés / %)
# Ne listez que les moteurs à déplacer pour chaque pose.
RELATIVE_POSES = [
    # 1 – rotation de la base vers la gauche
    {"shoulder_pan": +10},
    # 2 – rotation vers la droite
    {"shoulder_pan": -10},
    # 3 – retour centre + lever épaule
    {"shoulder_pan": 0, "shoulder_lift": -10},
    # 4 – fléchir le coude
    {"elbow_flex": +10},
    # 5 – roulis poignet dans un sens
    {"wrist_roll": +10},
    # 6 – roulis opposé
    {"wrist_roll": -10},
    # 7 – flex poignet
    {"wrist_flex": +10},
    # 8 – gripper ouvert
    {"gripper": +10},
    # 9 – gripper fermé
    {"gripper": -10},
    # 10 – tout à zéro (retour position initiale relative)
    {"shoulder_pan": 0, "shoulder_lift": 0,
     "elbow_flex": 0, "wrist_flex": 0,
     "wrist_roll": 0, "gripper": 0},
]
# ══════════════════════════════════════════════════════════════════════════════

print("=" * 60)
print("  MOUVEMENT SO-100  —  séquence multi-axes")
print("=" * 60)

# ── Imports ───────────────────────────────────────────────────────────────────
try:
    from lerobot.robots.so_follower.so_follower import SOFollower
    from lerobot.robots.so_follower.config_so_follower import SOFollowerRobotConfig
except ImportError as e:
    print(f"\n❌ Import échoué : {e}")
    print("   cd lerobot && pip3 install -e '.[feetech]'")
    sys.exit(1)

# ── Connexion ─────────────────────────────────────────────────────────────────
print(f"\n🔌 Connexion sur {PORT} ...")
config = SOFollowerRobotConfig(port=PORT, id=ROBOT_ID)
robot  = SOFollower(config)

try:
    robot.connect()
    print("   ✅ Connecté")
except Exception as e:
    print(f"   ❌ {e}")
    sys.exit(1)

# ── Position de départ ────────────────────────────────────────────────────────
start_obs = robot.get_observation()
# Dict  motor_name → valeur  (sans le suffixe .pos)
start: dict[str, float] = {
    k.removesuffix(".pos"): v
    for k, v in start_obs.items()
    if k.endswith(".pos")
}

print("\n📍 Position de départ :")
col = max(len(m) for m in start) + 2
for motor, val in start.items():
    print(f"   {motor:{col}s} = {val:7.2f}")


# ── Helpers ───────────────────────────────────────────────────────────────────
def interpolate(
    current: dict[str, float],
    target: dict[str, float],
    steps: int,
) -> list[dict[str, float]]:
    """Génère `steps` poses intermédiaires par interpolation linéaire."""
    frames = []
    for i in range(1, steps + 1):
        t = i / steps
        frame = {m: current[m] + (target[m] - current[m]) * t for m in current}
        frames.append(frame)
    return frames


def send_pose(robot: "SOFollower", pose: dict[str, float]) -> None:
    """Envoie une pose complète (motor→val) au robot."""
    robot.send_action({f"{m}.pos": v for m, v in pose.items()})


# ── Séquence de mouvements ────────────────────────────────────────────────────
print(f"\n🤖 Démarrage — {len(RELATIVE_POSES)} poses  "
      f"({STEPS} étapes × {1/STEP_HZ*1000:.0f} ms, pause {PAUSE_S} s) ...")
print("   [Ctrl+C pour arrêter]\n")

current_pose = dict(start)
period = 1.0 / STEP_HZ

try:
    for idx, rel_pose in enumerate(RELATIVE_POSES, start=1):
        # Calculer la cible absolue pour chaque moteur mentionné
        target_pose = dict(current_pose)
        for motor, delta in rel_pose.items():
            if motor in target_pose:
                target_pose[motor] = start[motor] + delta

        desc = ", ".join(f"{k}→{v:+.0f}" for k, v in rel_pose.items())
        print(f"  Pose {idx:02d}/{len(RELATIVE_POSES)} : {desc}")

        for frame in interpolate(current_pose, target_pose, STEPS):
            t0 = time.perf_counter()
            send_pose(robot, frame)
            elapsed = time.perf_counter() - t0
            sleep_t = period - elapsed
            if sleep_t > 0:
                time.sleep(sleep_t)

        current_pose = dict(target_pose)
        time.sleep(PAUSE_S)

    print("\n   ✅ Séquence terminée")

except KeyboardInterrupt:
    print("\n\n   ⏹  Arrêt manuel")

# ── Retour position initiale ──────────────────────────────────────────────────
print("\n↩️  Retour à la position de départ ...")
for frame in interpolate(current_pose, start, STEPS * 2):
    t0 = time.perf_counter()
    send_pose(robot, frame)
    elapsed = time.perf_counter() - t0
    sleep_t = period - elapsed
    if sleep_t > 0:
        time.sleep(sleep_t)
print("   ✅ Retour effectué")

# ── Déconnexion ───────────────────────────────────────────────────────────────
try:
    robot.disconnect()
    print("\n🔌 Déconnecté")
except Exception as e:
    print(f"\n⚠️  Erreur déconnexion : {e}")

print("\n" + "=" * 60)
print("  ✅ TERMINÉ")
print("=" * 60)
