#!/usr/bin/env python3
"""Camera intrinsic calibration using a ChArUco board.

Compared with checkerboards, ChArUco often calibrates more robustly with
partial views and moderate blur because marker IDs improve corner association.

Usage
-----
python3 sim_to_real/calibrate_camera_charuco.py \
  --camera-id 0 \
  --squares-x 7 --squares-y 5 \
  --square-length-m 0.03 --marker-length-m 0.022 \
  --min-frames 25 --outlier-trim-ratio 0.25
"""

from __future__ import annotations

import argparse

import cv2
import numpy as np

from aruco_utils import save_camera_calibration


# Generated by GitHub Copilot
def _build_charuco_board(
    squares_x: int,
    squares_y: int,
    square_length_m: float,
    marker_length_m: float,
    dictionary: cv2.aruco.Dictionary,
):
    """Create a ChArUco board object across OpenCV versions."""
    if hasattr(cv2.aruco, "CharucoBoard"):
        return cv2.aruco.CharucoBoard(
            (squares_x, squares_y), square_length_m, marker_length_m, dictionary
        )
    if hasattr(cv2.aruco, "CharucoBoard_create"):
        return cv2.aruco.CharucoBoard_create(
            squares_x, squares_y, square_length_m, marker_length_m, dictionary
        )
    raise RuntimeError("OpenCV ArUco ChArUco API not available in this build.")


# Generated by GitHub Copilot
def _interpolate_charuco(gray: np.ndarray, board, corners, ids):
    """Interpolate ChArUco corners from marker detections."""
    retval, charuco_corners, charuco_ids = cv2.aruco.interpolateCornersCharuco(
        corners, ids, gray, board
    )
    return int(retval), charuco_corners, charuco_ids


# Generated by GitHub Copilot
def _board_chessboard_corners(board) -> np.ndarray:
    """Return board chessboard corners as (N,3) float32 array."""
    if hasattr(board, "getChessboardCorners"):
        pts = board.getChessboardCorners()
    else:
        pts = board.chessboardCorners
    return np.asarray(pts, dtype=np.float32)


# Generated by GitHub Copilot
def _frame_rms_errors_charuco(
    all_charuco_corners: list[np.ndarray],
    all_charuco_ids: list[np.ndarray],
    board,
    rvecs: tuple[np.ndarray, ...],
    tvecs: tuple[np.ndarray, ...],
    camera_matrix: np.ndarray,
    dist_coeffs: np.ndarray,
) -> np.ndarray:
    """Compute per-frame RMSE using ChArUco corner reprojection."""
    board_pts = _board_chessboard_corners(board)
    errors: list[float] = []

    for i in range(len(all_charuco_corners)):
        ids = all_charuco_ids[i].flatten().astype(np.int32)
        objp = board_pts[ids]
        proj, _ = cv2.projectPoints(objp, rvecs[i], tvecs[i], camera_matrix, dist_coeffs)

        obs = all_charuco_corners[i].reshape(-1, 2)
        est = proj.reshape(-1, 2)
        diff = obs - est
        rmse = float(np.sqrt(np.mean(np.sum(diff**2, axis=1))))
        errors.append(rmse)

    return np.asarray(errors, dtype=np.float64)


# Generated by GitHub Copilot
def main() -> None:
    """Capture ChArUco frames and calibrate camera intrinsics."""
    parser = argparse.ArgumentParser(description="Camera intrinsic calibration via ChArUco board.")
    parser.add_argument("--camera-id", type=int, default=0)
    parser.add_argument("--squares-x", type=int, default=7)
    parser.add_argument("--squares-y", type=int, default=5)
    parser.add_argument("--square-length-m", type=float, default=0.03)
    parser.add_argument("--marker-length-m", type=float, default=0.022)
    parser.add_argument("--dict", default="DICT_4X4_50")
    parser.add_argument("--min-frames", type=int, default=20)
    parser.add_argument("--min-charuco-corners", type=int, default=8)
    parser.add_argument("--outlier-trim-ratio", type=float, default=0.25)
    args = parser.parse_args()

    if args.marker_length_m >= args.square_length_m:
        raise ValueError("--marker-length-m must be smaller than --square-length-m")

    dict_id = getattr(cv2.aruco, args.dict)
    aruco_dict = cv2.aruco.getPredefinedDictionary(dict_id)
    detector = cv2.aruco.ArucoDetector(aruco_dict, cv2.aruco.DetectorParameters())

    board = _build_charuco_board(
        args.squares_x,
        args.squares_y,
        args.square_length_m,
        args.marker_length_m,
        aruco_dict,
    )

    all_charuco_corners: list[np.ndarray] = []
    all_charuco_ids: list[np.ndarray] = []

    cap = cv2.VideoCapture(args.camera_id)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open camera {args.camera_id}")

    print("Show the ChArUco board. Press SPACE to capture, 'q' to finish.")
    image_size: tuple[int, int] | None = None

    while True:
        ok, frame = cap.read()
        if not ok:
            continue

        image_size = (frame.shape[1], frame.shape[0])
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        corners, ids, _ = detector.detectMarkers(gray)

        display = frame.copy()
        detected_count = 0

        if ids is not None and len(ids) > 0:
            cv2.aruco.drawDetectedMarkers(display, corners, ids)
            detected_count, ccorners, cids = _interpolate_charuco(gray, board, corners, ids)
            if cids is not None and ccorners is not None and len(cids) > 0:
                cv2.aruco.drawDetectedCornersCharuco(display, ccorners, cids)
        else:
            ccorners = None
            cids = None

        cv2.putText(
            display,
            f"captures: {len(all_charuco_corners)}/{args.min_frames}  detected: {detected_count}",
            (10, 30),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (0, 255, 0),
            2,
        )
        cv2.imshow("calibrate_camera_charuco", display)

        key = cv2.waitKey(1) & 0xFF
        if key == ord(" ") and ccorners is not None and cids is not None:
            if len(cids) >= args.min_charuco_corners:
                all_charuco_corners.append(ccorners.copy())
                all_charuco_ids.append(cids.copy())
                print(f"Captured frame {len(all_charuco_corners)} with {len(cids)} corners")
            else:
                print(
                    f"Rejected frame: only {len(cids)} ChArUco corners "
                    f"(< {args.min_charuco_corners})"
                )
        elif key == ord("q"):
            break

    cap.release()
    cv2.destroyAllWindows()

    if len(all_charuco_corners) < args.min_frames:
        raise RuntimeError(
            f"Only {len(all_charuco_corners)} captures, need at least {args.min_frames}."
        )

    rms, camera_matrix, dist_coeffs, rvecs, tvecs = cv2.aruco.calibrateCameraCharuco(
        all_charuco_corners,
        all_charuco_ids,
        board,
        image_size,
        None,
        None,
    )

    if args.outlier_trim_ratio > 0.0 and len(all_charuco_corners) > args.min_frames:
        trim_count = int(round(len(all_charuco_corners) * args.outlier_trim_ratio))
        keep_count = max(args.min_frames, len(all_charuco_corners) - trim_count)

        if keep_count < len(all_charuco_corners):
            frame_errors = _frame_rms_errors_charuco(
                all_charuco_corners,
                all_charuco_ids,
                board,
                rvecs,
                tvecs,
                camera_matrix,
                dist_coeffs,
            )
            keep_idx = np.argsort(frame_errors)[:keep_count]
            keep_idx = np.sort(keep_idx)

            all_charuco_corners = [all_charuco_corners[i] for i in keep_idx]
            all_charuco_ids = [all_charuco_ids[i] for i in keep_idx]

            rms, camera_matrix, dist_coeffs, _, _ = cv2.aruco.calibrateCameraCharuco(
                all_charuco_corners,
                all_charuco_ids,
                board,
                image_size,
                None,
                None,
            )

            print(
                f"\nOutlier filtering: kept {keep_count}/{len(frame_errors)} frames "
                f"(trimmed {len(frame_errors) - keep_count})."
            )

    print(f"\nRMS reprojection error: {rms:.4f} px")
    print(f"camera_matrix=\n{camera_matrix}")
    print(f"dist_coeffs=\n{dist_coeffs.ravel()}")

    save_camera_calibration(camera_matrix, dist_coeffs)
    print("\nSaved to sim_to_real/calibration/camera_intrinsics.npz")


if __name__ == "__main__":
    main()
