#!/usr/bin/env python3
"""Generate a printable ChArUco board image.

ChArUco boards are typically more robust than plain checkerboards for
calibration in imperfect lighting and viewpoints.

Usage
-----
python3 sim_to_real/generate_charuco_board.py \
  --squares-x 7 --squares-y 5 \
  --square-length-mm 30 --marker-length-mm 22 \
  --out sim_to_real/calibration/charuco_7x5_30mm_22mm.png
"""

from __future__ import annotations

import argparse
from pathlib import Path

import cv2


# Generated by GitHub Copilot
def _build_charuco_board(
    squares_x: int,
    squares_y: int,
    square_length_m: float,
    marker_length_m: float,
    dictionary: cv2.aruco.Dictionary,
):
    """Create a ChArUco board compatible with OpenCV version in use."""
    if hasattr(cv2.aruco, "CharucoBoard"):
        return cv2.aruco.CharucoBoard(
            (squares_x, squares_y), square_length_m, marker_length_m, dictionary
        )
    if hasattr(cv2.aruco, "CharucoBoard_create"):
        return cv2.aruco.CharucoBoard_create(
            squares_x, squares_y, square_length_m, marker_length_m, dictionary
        )
    raise RuntimeError("OpenCV ArUco ChArUco API not available in this build.")


# Generated by GitHub Copilot
def _draw_board_image(board, width_px: int, height_px: int, margin_px: int):
    """Render board image with compatibility across OpenCV versions."""
    if hasattr(board, "generateImage"):
        return board.generateImage((width_px, height_px), marginSize=margin_px, borderBits=1)
    return cv2.aruco.drawPlanarBoard(board, (width_px, height_px), margin_px, 1)


# Generated by GitHub Copilot
def main() -> None:
    """Generate a ChArUco board PNG from command-line parameters."""
    parser = argparse.ArgumentParser(description="Generate printable ChArUco board PNG.")
    parser.add_argument("--squares-x", type=int, default=7, help="Number of board squares along x.")
    parser.add_argument("--squares-y", type=int, default=5, help="Number of board squares along y.")
    parser.add_argument(
        "--square-length-mm",
        type=float,
        default=30.0,
        help="Square side length in millimetres.",
    )
    parser.add_argument(
        "--marker-length-mm",
        type=float,
        default=22.0,
        help="ArUco marker side length in millimetres (must be < square length).",
    )
    parser.add_argument("--dict", default="DICT_4X4_50", help="ArUco dictionary name.")
    parser.add_argument("--width-px", type=int, default=3508, help="Output width in pixels.")
    parser.add_argument("--height-px", type=int, default=2480, help="Output height in pixels.")
    parser.add_argument("--margin-px", type=int, default=80, help="White margin around board in pixels.")
    parser.add_argument(
        "--out",
        default="sim_to_real/calibration/charuco_board.png",
        help="Output PNG path.",
    )
    args = parser.parse_args()

    if args.marker_length_mm >= args.square_length_mm:
        raise ValueError("--marker-length-mm must be smaller than --square-length-mm")

    dict_id = getattr(cv2.aruco, args.dict)
    aruco_dict = cv2.aruco.getPredefinedDictionary(dict_id)

    square_length_m = args.square_length_mm / 1000.0
    marker_length_m = args.marker_length_mm / 1000.0

    board = _build_charuco_board(
        args.squares_x,
        args.squares_y,
        square_length_m,
        marker_length_m,
        aruco_dict,
    )
    img = _draw_board_image(board, args.width_px, args.height_px, args.margin_px)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    cv2.imwrite(str(out_path), img)

    print(f"Saved board: {out_path}")
    print(
        "Board params: "
        f"squares={args.squares_x}x{args.squares_y}, "
        f"square={args.square_length_mm:.1f} mm, "
        f"marker={args.marker_length_mm:.1f} mm"
    )
    print("Print at 100% scale (disable 'fit to page').")


if __name__ == "__main__":
    main()
