#!/usr/bin/env python3
"""Evaluate a trained PPO or SAC policy.

Automatically detects the algorithm from the model filename or from
a ``--algo`` flag.

Usage
-----
    # Evaluate best model saved during training:
    python scripts/evaluate_policy.py \
        --model outputs/logs/ppo_so100_pick_place/best_model/best_model.zip \
        --env SO100PickPlace-v0 \
        --algo ppo \
        --episodes 10

    python scripts/evaluate_policy.py \
        --model outputs/logs/sac_so100_pick_place/best_model/best_model.zip \
        --env SO100PickPlace-v0 \
        --algo sac \
        --render
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
from stable_baselines3 import PPO, SAC

# Generated by GitHub Copilot
# Support direct script execution with the repository's src/ layout.
project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root / "src"))

import so100_mujoco_rl.envs  # noqa: F401 — registers envs
import gymnasium as gym

_ALGO_MAP = {"ppo": PPO, "sac": SAC}


def _infer_algo(model_path: str) -> str:
    """Guess algo from model filename prefix."""
    lower = model_path.lower()
    if "sac" in lower:
        return "sac"
    return "ppo"


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate a trained SB3 policy.")
    parser.add_argument("--model", required=True, help="Path to .zip model file")
    parser.add_argument("--env", default="SO100PickPlace-v0", help="Gymnasium env id")
    parser.add_argument(
        "--algo",
        choices=["ppo", "sac"],
        default=None,
        help="Algorithm class to use for loading (inferred from filename if omitted)",
    )
    parser.add_argument("--episodes", type=int, default=10, help="Number of eval episodes")
    parser.add_argument(
        "--render",
        action="store_true",
        help="Render during evaluation (opens a window)",
    )
    parser.add_argument("--deterministic", action="store_true", default=True)
    args = parser.parse_args()

    algo_name = args.algo or _infer_algo(args.model)
    AlgoClass = _ALGO_MAP[algo_name]

    render_mode = "human" if args.render else None
    env = gym.make(args.env, render_mode=render_mode)

    print(f"\nLoading {algo_name.upper()} model: {args.model}")
    model = AlgoClass.load(args.model, env=env)

    episode_rewards: list[float] = []
    episode_lengths: list[int] = []
    successes: list[bool] = []

    for ep in range(args.episodes):
        obs, _ = env.reset()
        total_reward = 0.0
        length = 0
        terminated = truncated = False

        while not (terminated or truncated):
            action, _ = model.predict(obs, deterministic=args.deterministic)
            obs, reward, terminated, truncated, info = env.step(action)
            total_reward += float(reward)
            length += 1

        episode_rewards.append(total_reward)
        episode_lengths.append(length)
        # Consider success if the last info dict has a relevant key, or reward > threshold.
        successes.append(info.get("success_bonus", 0.0) > 0)
        print(f"  Episode {ep+1:2d}: reward={total_reward:+8.2f}  length={length:3d}")

    env.close()

    print("\n--- Summary ---")
    print(f"  Mean reward  : {np.mean(episode_rewards):.2f} ± {np.std(episode_rewards):.2f}")
    print(f"  Mean length  : {np.mean(episode_lengths):.1f}")
    print(f"  Success rate : {sum(successes)}/{len(successes)}")


if __name__ == "__main__":
    main()
