#!/usr/bin/env python3
"""Record a video of a trained policy on SO100Grab-v0.

Usage
-----
    PYTHONPATH=src python3 scripts/record_grab_video.py \
        --model outputs/models/ppo_SO100Grab-v0_final.zip \
        --env-config configs/env/so100_grab_fixed.yaml \
        --out outputs/videos/grab_rollout.mp4 \
        --episodes 3

Speed / slow-motion
--------------------
Each env step advances the simulation by n_substeps * timestep = 5 * 0.004s
= 0.02s (50 Hz). To play back at real-time speed, use --fps 50 (default).
Use a lower --fps for slow motion (e.g. --fps 25 = half speed) or a higher
--fps for fast-forward (e.g. --fps 100 = double speed).

Camera
------
Pass --camera overhead or --camera side_cam to use one of the scene's fixed
cameras (see assets/robots/so100/so100_feuille_scene.xml). Omit for the
default free camera.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import gymnasium as gym
import imageio
import mujoco
from stable_baselines3 import PPO

# Generated by GitHub Copilot
# Support direct script execution with the repository's src/ layout.
project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root / "src"))

import so100_mujoco_rl.envs  # noqa: F401 — registers envs


def main() -> None:
    parser = argparse.ArgumentParser(description="Record a policy rollout video.")
    parser.add_argument("--model", required=True, help="Path to .zip SB3 model")
    parser.add_argument("--env", default="SO100Grab-v0", help="Gymnasium env id")
    parser.add_argument(
        "--env-config",
        default=None,
        help="Optional env YAML path (e.g. configs/env/so100_grab_fixed.yaml)",
    )
    parser.add_argument("--out", default="outputs/videos/grab_rollout.mp4", help="Output video path")
    parser.add_argument("--episodes", type=int, default=3, help="Number of episodes to record")
    parser.add_argument("--camera", default=None, help="Camera name (e.g. 'overhead', 'side_cam')")
    parser.add_argument("--width", type=int, default=640)
    parser.add_argument("--height", type=int, default=480)
    parser.add_argument("--fps", type=int, default=50, help="Output video FPS (50 = real-time)")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--deterministic", action="store_true", default=True)
    args = parser.parse_args()

    env_kwargs = {"render_mode": None}
    if args.env_config is not None:
        env_kwargs["env_config"] = args.env_config

    env = gym.make(args.env, **env_kwargs)
    model = PPO.load(args.model)

    renderer = mujoco.Renderer(env.unwrapped.model, height=args.height, width=args.width)
    camera = args.camera if args.camera is not None else -1

    frames: list = []
    obs, _ = env.reset(seed=args.seed)
    for ep in range(args.episodes):
        terminated = truncated = False
        ep_reward = 0.0
        while not (terminated or truncated):
            renderer.update_scene(env.unwrapped.data, camera=camera)
            frames.append(renderer.render())

            action, _ = model.predict(obs, deterministic=args.deterministic)
            obs, reward, terminated, truncated, info = env.step(action)
            ep_reward += float(reward)

        print(f"Episode {ep + 1}: reward={ep_reward:+.2f}  success={info.get('success_bonus', 0.0) > 0}")
        obs, _ = env.reset()

    renderer.close()
    env.close()

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    imageio.mimsave(out_path, frames, fps=args.fps)
    print(f"\nSaved {len(frames)} frames ({len(frames) / args.fps:.1f}s) to {out_path}")


if __name__ == "__main__":
    main()
