#!/usr/bin/env python3
"""Train a PPO policy on the SO-100 reach-and-grab task.

Usage
-----
    python scripts/train_ppo_so100_grab.py
"""

import sys
from pathlib import Path

# Generated by GitHub Copilot
# Support direct script execution with the repository's src/ layout.
project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root / "src"))

from so100_mujoco_rl.train.train_sb3 import train

if __name__ == "__main__":
    train("configs/train/ppo_so100_grab.yaml")
