# Generated by GitHub Copilot
"""Launch MuJoCo viewer for a scene file."""
import sys
import mujoco
import mujoco.viewer

path = sys.argv[1] if len(sys.argv) > 1 else "assets/scene_table.xml"
m = mujoco.MjModel.from_xml_path(path)
d = mujoco.MjData(m)

with mujoco.viewer.launch_passive(m, d) as v:
    while v.is_running():
        mujoco.mj_step(m, d)
        v.sync()
